import { randomUUID } from "node:crypto";
import type { LoginInput, RegisterInput } from "../schemas/index.js";
import type { IAuthResponse, ISessionUser } from "../types/auth.interface.js";
import { Role } from "../types/user.interface.js";

const registerUser = async (
	userData: RegisterInput,
): Promise<IAuthResponse> => {
	// 1. check for existing user - if present ask to login
	// 2. encrypt password if present
	// 3. create new user & save
	// 4. send acknowledgement/response
	const { fullName, username, email, password } = userData;

	const successMessage = `User ${fullName} registered successfully`;

	const response: IAuthResponse = await {
		message: successMessage,
	};
	return response;
};

const loginUser = async (userData: LoginInput): Promise<IAuthResponse> => {
	// 1. check for user
	// 2. check for password if present
	// 3. perform login
	// 4. get user info from database
	// 5. store user info based on strategy (like token)
	const { username, email, password } = userData;

	const userSession: ISessionUser = await {
		id: randomUUID(), // update with the ID generated by DB
		username,
		role: Role.USER, // assign custom role here if you want
	};

	const successMessage = `User ${username} with email ${email} logged in successfully`;

	const response: IAuthResponse = await {
		user: userSession,
		message: successMessage,
	};
	return response;
};

const logoutUser = async (
	userData: ISessionUser | undefined,
): Promise<IAuthResponse> => {
	// 1. check if user is already is logged out
	// 2. perform logout by using existing user info
	// handle DB logout operations using user data
	const successMessage = `User ${userData?.username} logged out successfully`;
	const response: IAuthResponse = await { message: successMessage };
	return response;
};

export const authServices = { registerUser, loginUser, logoutUser };
